trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /src/main/resources/test-*.yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'